forms/login.py
from flask_wtf import Form
import wtforms as wt
from wtforms.validators import DataRequired, EqualTo, ValidationError


class LoginForm(Form):
    usuario = wt.TextField("Usuario", validators=[DataRequired()])
    contrasena = wt.PasswordField("Contraseña", validators=[DataRequired()])

controllers/campagnas.py
# -*- coding: utf-8 -*-
from flask import (
    Blueprint,
    current_app,
    Response,
    abort,
    jsonify,
    request,
    session,
    redirect,
    flash,
    render_template,
    url_for
)
from flask_login import login_required, current_user
from sqlalchemy import Table
import mailchimp
from utils import get_mailchimp_api
from eventos import get_event_data
from time import timezone
from datetime import datetime, timedelta
import json
import math

campagnas = Blueprint('campagnas', __name__)


def initialize_app(app):
    app.register_blueprint(campagnas)


@campagnas.route("/campagnas", methods=['GET', 'POST'])
@login_required
def index(message=None, folder=None):
    data = {
        'message': message,
        'current_folder': folder
    }
    return render_template('campagnas/list.html', **data)


def paginate_data(data, pagina, folder=0, per_page=25):
    data['page'] = pagina
    data['next_num'] = pagina + 1
    data['prev_num'] = pagina - 1
    data['pages'] = math.ceil(data['total'] / per_page)
    data['per_page'] = per_page
    if pagina > 0:
        data['has_previus'] = True
    if pagina < data['pages']:
        data['has_next'] = True
    return data


@campagnas.route("/campagnas/ajax/listar", methods=['GET', 'POST'])
@campagnas.route("/campagnas/ajax/listar/<int:pagina>", methods=['GET', 'POST'])
@login_required
def ajax_listar_campagnas(pagina=0):
    per_page = 25
    m = get_mailchimp_api()
    campaignList = m.campaigns.list(start=pagina)
    campaignList = paginate_data(campaignList, pagina)
    return json.dumps(campaignList)


@campagnas.route("/campagnas/ajax/buscar", methods=['POST'])
@login_required
def ajax_buscar_campagnas(pagina=0):
    per_page = 25
    filters = {'title': request.form.get('title', ''),
               'exact': False,
               'status': ','.join(request.form.getlist('status')),
               'folder_id': ','.join(request.form.getlist('folder_id')),
               'sendtime_start': request.form.get('sendtime_start', ''),
               'sendtime_end': request.form.get('sendtime_end', ''),
               'folder_id': request.form.get('folder_id', '')
               }
    m = get_mailchimp_api()
    campaignList = m.campaigns.list(filters=filters)
    campaignList = paginate_data(campaignList, pagina, per_page=per_page)

    return json.dumps(campaignList)


@campagnas.route("/campagnas/ajax/folders", methods=['GET', 'POST'])
def ajax_folder_list():
    return json.dumps(get_mailchimp_api().folders.list("campaign"))


@campagnas.route("/campagnas/folder/<folder>", methods=['GET', 'POST'])
@login_required
def folder(folder=None):
    return index(None, folder)


@campagnas.route("/campagnas/folder/setArea", methods=['POST'])
@login_required
def changeFolder():
    folder_id = request.form['area']
    id_camp = request.form['id']
    try:
        m = get_mailchimp_api()
        details = m.campaigns.update(id_camp, 'options',
                                     {'folder_id': folder_id})
    except mailchimp.Error, e:
        return "Ha ocurrido un error con mailchimp", e

    return index(None, details['data']['folder_id'])


@campagnas.route("/campagnas/folder/remove/<area_id>", methods=['POST'])
@login_required
def deleteFolder(area_id):
    area = area_id
    folderType = "campaign"
    try:
        print(area)
        m = get_mailchimp_api()
        folder_id = m.folders.delete(area, folderType)
        print(folder_id)
    except mailchimp.Error, e:
        return "Ha ocurrido un error con mailchimp", e
    return index(None, folder_id)


@campagnas.route("/campagnas/folder/add/", methods=['POST'])
@login_required
def addFolder():
    name = request.form['name']
    folderType = "campaign"
    try:
        m = get_mailchimp_api()
        folder_id = m.folders.add(name, folderType)
    except mailchimp.Error, e:
        return "Ha ocurrido un error al intentar conectar con mailchimp"
    return index(None, folder_id)


@campagnas.route("/campagnas/create", methods=['GET'])
@login_required
def create():
    try:
        m = get_mailchimp_api()
        lists = m.lists.list(sort_field='web', limit=100)
        template_lists = m.templates.list()
        folderList = m.folders.list("campaign")
    except mailchimp.Error, e:
        return "Ha ocurrido un error con mailchimp<br>"+str(e)
    data = {
        'lists': lists['data'],
        'template_lists': template_lists['user'],
        'areaList': folderList
    }
    return render_template('campagnas/create.html',
                           title="Crear campañas",
                           **data)


@campagnas.route("/campagnas/create", methods=['POST'])
@login_required
def create2():
    type = 'regular'
    options = {
        'list_id': request.form['emailList'],
        'subject': request.form['subject'],
        'from_email': request.form['outgoinEmail'],
        'from_name': request.form['outgoinName'],
        'title': request.form['campaignName'],
        'auto_footer': False,
        'folder_id': request.form['folder']
    }
    content = {
        'html': request.form['html']
    }
    # se quita como ya no existen eventos
    # event_id = int(request.form['event_id'])
    # if (event_id > 0):
    #     event_data = get_event_data(event_id)
    #     content = {
    #         'html': replace_tags(request.form['html'], event_data)
    #     }
    m = get_mailchimp_api()
    try:
        if 'id' in request.form:
            cid = request.form['id']
            detailsVar = m.campaigns.update(cid, 'options', options)
            details2 = m.campaigns.update(cid, 'content', content)
            errors = detailsVar['errors']
            detailsVar = detailsVar['data']
        else:
            detailsVar = m.campaigns.create(type, options, content)
    except mailchimp.Error, e:
        return index("<div class='alert alert-danger'>Ha ocurrido un error \
                      con mailchimp "+str(e)+"</div>")
    return details(detailsVar["id"])


@campagnas.route("/campagnas/detalles/<id>", methods=['GET'])
@login_required
def details(id):
    try:
        m = get_mailchimp_api()
        details = m.campaigns.list({'campaign_id': id})
        list_id = details['data'][0].get("list_id", 0)
        current_list = m.lists.list(filters={'list_id': list_id})

    except mailchimp.Error, e:
        flash("Ha ocurrido un error: " + str(e), "error")
    campaign = details['data'][0]
    set_current_gmt(campaign)
    if campaign['status'] == "sent":
        campaign['status'] = "Enviado"
    elif campaign['status'] == "save":
        campaign['status'] = "Guardado"
    elif campaign['status'] == "sending":
        campaign['status'] = "Enviando"
    data = {
        'campaign': campaign,
        'current_list': current_list['data'][0]
    }
    return render_template('campagnas/details.html',
                           title="Detalles",
                           **data)


@campagnas.route("/campagnas/edit/<id_>", methods=['GET'])
@login_required
def edit(id_):
    try:
        m = get_mailchimp_api()
        details = m.campaigns.list({'campaign_id': id_})
        content = m.campaigns.content(id_)
        lists = m.lists.list(limit=100)
        template_lists = m.templates.list()
        folderList = m.folders.list("campaign")
    except mailchimp.Error, e:
        return index("Ha ocurrido un error con mailchimp"+str(e))

    html = (clean_html(content['html']))

    data = {
        'campaign': details['data'][0],
        'html': html,
        'lists': lists['data'],
        'template_lists': template_lists['user'],
        'areaList': folderList
    }
    return render_template('campagnas/edit.html',
                           title="Editar campaña",
                           **data)


@campagnas.route("/campagnas/clone/<id>", methods=['GET'])
@login_required
def clone(id):
    try:
        m = get_mailchimp_api()
        details = m.campaigns.list({'campaign_id': id})
        content = m.campaigns.content(id)
        lists = m.lists.list(limit=100)
        template_lists = m.templates.list()
        folderList = m.folders.list("campaign")
    except mailchimp.Error, e:
        return index("Ha ocurrido un error con mailchimp"+str(e))
    html = replace_rewards_unsubcribe(content['html'])
    details['data'][0]['id'] = None
    data = {
        'campaign': details['data'][0],
        'html': html,
        'lists': lists['data'],
        'template_lists': template_lists['user'],
        'areaList': folderList
    }
    return render_template('campagnas/edit.html',
                           title="Editar campaña",
                           **data)


@campagnas.route("/campagnas/send", methods=['POST'])
@login_required
def send():
    id_ = request.form['id']
    try:
        m = get_mailchimp_api()
        status = m.campaigns.send(id_)
    except mailchimp.Error, e:
        flash("Se encontraron errores con mailchimp " + str(e), "error")
    return redirect(url_for(".details", id=id_))


@campagnas.route("/campagnas/sendTest", methods=['POST'])
@login_required
def sendTest():
    emails = request.form.getlist('email')
    campaignId = request.form['campaignId']
    try:
        m = get_mailchimp_api()
        details = m.campaigns.send_test(campaignId, emails)
        flash("pruebas enviadas correctamente", "success")
    except mailchimp.Error, e:
        flash("Ha ocurrido un error al conectar con mailchimp:\n" + str(e),
              "error")
        return redirect(url_for(".details", id=campaignId))
    return redirect(url_for(".details", id=campaignId))


@campagnas.route("/campagnas/delete/<campaign_id>", methods=['POST'])
@login_required
def delete(campaign_id):
    try:
        m = get_mailchimp_api()
        status = m.campaigns.delete(campaign_id)
    except mailchimp.CampaignDoesNotExistError:
        return json.dumps({"error": u"la campaña no existe"})
    except mailchimp.Error, e:
        return json.dumps({"error": u"Ha ocurrido un error con mailchimp"})

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Mailing | CDT</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/css/font-awesome.min.css">
  <link rel="stylesheet" href="/static/css/checkbox.css">

  <!-- Ionicons -->
  <link rel="stylesheet" href="/static/css/ionicons.min.css">
  <link rel="stylesheet" href="/static/css/select2.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/plugins/SmartNotification/SmartNotification.css">
  <link rel="stylesheet" href="/static/css/sweetalert.css">
  <link rel="stylesheet" href="/static/css/bootstrap-datetimepicker.css">

  {% block extra_css%}{%endblock%}

  <link rel="stylesheet" href="/static/css/AdminLTE.min.css">
  <link rel="stylesheet" href="/static/css/skins/_all-skins.min.css">

</head>
<body class="hold-transition skin-purple-light sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="/" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>CDT</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Mailing</b> <small>CDT</small></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="/static/img/user2-160x160.jpg" class="user-image" alt="User Image">
              <span class="hidden-xs">{{current_user.doc.user_name}}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="/static/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                <p>{{current_user.doc.user_name}}
                  <small>{{current_user.doc.user_login}}</small>
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="/auth/profile" title="Ver Perfil" class="btn btn-default btn-flat">Mi perfil</a>
                </div>
                <div class="pull-right">
                  <a href="/auth/logout" class="btn btn-default btn-flat">Cerrar sesion</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      
    </nav>
  </header>

  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <ul class="sidebar-menu">
        <li>
          <a href="/">
            <i class="fa fa-home"></i> <span>Inicio</span>
          </a>
        </li>
        
        <li>
          <a href="/campagnas">
            <i class="fa fa-envelope-o" aria-hidden="true"></i> <span>Mailing</span>
          </a>
        </li>
        
        <li>
          <a href="/correos">
            <i class="fa fa fa-th-list" aria-hidden="true"></i> <span>Lista de Correos</span>
          </a>
        </li>

        <li>
          <a href="/eventos">
            <i class="fa fa fa-lg fa-fw fa-calendar"></i> <span>Eventos</span>
          </a>
        </li>
        <li>
          <a href="/plantillas">
            <i class="fa fa-file-powerpoint-o"></i> <span>Plantillas</span>
          </a>
        </li>
        {% if current_user.doc.user_role.lower() == "admin" or  current_user.doc.user_role.lower() == "root" %}
          <li>
          <a href="/auth/users"><i class="fa fa-lg fa-fw fa-street-view"></i> <span>Usuarios</span></a>
          </li>
          {% endif %}
        {%block options%} {%endblock%}
      </ul>
    </section>
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
  {% block content_wrapper %}
   
    <!-- Main content -->
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <!-- <strong>Title</strong> --> {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    <section class="content">
    {%block content%} {%endblock%}
    </section>
    <!-- /.content -->
    {%endblock%}
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <strong>Copyright &copy; 2017 <a href="http://nice.cl">Nice Desarrollo</a>.</strong> Todos los derechos
    reservados.
  </footer>
  
</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.3 -->
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/plugins/SmartNotification/SmartNotification.min.js"></script>
<script src="/static/js/sweetalert-dev.js"></script>

<script src="/static/js/select2.min.js"></script>
<script src="/static/js/holder.js"></script>
<script src="/static/js/d3.v3.min.js"></script>
<script src="/static/js/nv.d3.min.js"></script>
<script src="/static/js/moment.min.js"></script>
<script src="/static/js/bootstrap-datetimepicker.min.js"></script>


<script src="/static/js/app.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          {%if category =="error"%}
            $.smallBox({
                title: "Se ha producido un error",
                content : "{{message | replace('\n', '<br/>') | safe}}",
                color : "#C46A69",
                timeout: 10000,
                iconSmall : "fa fa-warning shake animated"
              });
          {%else%}
            $.smallBox({
                title: "Mensaje:",
                content : "{{message| replace('\n', '<br/>') | safe}}<br/>",
                color : "#296191",
                timeout: 10000,
                icon : "fa fa-bell fa-small swing animated"
              });
          {%endif%}
        {% endfor %}
      {% endif %}
  {% endwith %}
  });
</script>
<script type="text/javascript">
      $(function(){
        $('select').select2();
        $('body').hide().fadeIn(200);
        window.onbeforeunload = function(e) {
          swal({
              text: 'Cargando Información',
              allowOutsideClick: false
          })
          swal.showLoading()
        };
      })
</script>
{% block extra_js%}{%endblock%}
</body>
</html>

templates/form_helper.html
{# -----  diferentes tipos de campos ------ #}
{% macro render_field(form, field, kwargs={}, caller=None) %}
  {% set has_error = field.errors | length > 0 %}
  <div class="form-group{{ ' has-error' if has_error else '' }}">
    <label for="{{ field.id }}">{{ field.label.text }}{% if field.flags.required %} *{% endif %}</label>
      {% if field.type != 'BooleanField' %}
        {% set _dummy = kwargs.setdefault('class', 'form-control') %}
      {% else %}
        {% set _dummy = kwargs.setdefault('data-toggle', 'toggle') %}
        {% set _dummy = kwargs.setdefault('data-on', 'Activado') %}
        {% set _dummy = kwargs.setdefault('data-off', 'Desactivado') %}
      {% endif %}
      {{ field(**kwargs)|safe }}
      {% if field.description %}
        <p class="help-block">{{ field.description }}</p>
      {% endif %}
  </div>
{% endmacro %}

{% macro render_horizontal_field(form, field, kwargs={}, caller=None) %}
  {% set has_error = field.errors | length > 0 %}
  <div class="form-group{{ ' has-error' if has_error else '' }}">
    <label for="{{ field.id }}" class="col-sm-2 col-lg-3 control-label">
      {% if field.flags.required %}<span class="text-red">*</span> {% endif %}{{ field.label.text }}
    </label>
    <div class="col-sm-10 col-lg-9">
      {% if field.flags.required %}
        {% set _dummy = kwargs.setdefault('required', 'required') %}
      {% endif %}
      {% if field.type != 'BooleanField' %}
        {% set _dummy = kwargs.setdefault('class', 'form-control') %}
      {% else %}
        {% set _dummy = kwargs.setdefault('data-toggle', 'toggle') %}
        {% set _dummy = kwargs.setdefault('data-on', 'Activado') %}
        {% set _dummy = kwargs.setdefault('data-off', 'Desactivado') %}
      {% endif %}
      {{ field(**kwargs)|safe }}
      {% for error in field.errors%}
        <p class="help-block">{{ error }}</p>
      {%endfor%}

    </div>
  </div>
{% endmacro %}

{% macro render_form_fields(form, form_opts=None, horizontal=False) %}
    {% if form.hidden_tag is defined %}
        {{ form.hidden_tag() }}
    {% else %}
        {% if csrf_token %}
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        {% endif %}
        {% for f in form if f.widget.input_type == 'hidden' %}
            {{ f }}
        {% endfor %}
    {% endif %}

    {% if form_opts and form_opts.form_rules %}
        {% for r in form_opts.form_rules %}
            {{ r(form, form_opts=form_opts) }}
        {% endfor %}
    {% else %}
        {% for f in form if f.widget.input_type != 'hidden' %}
          {% if form_opts %}
            {% set kwargs = form_opts.widget_args.get(f.name, {}) %}
          {% else %}
            {% set kwargs = {} %}
          {% endif %}
          {% if horizontal%}
            {{ render_horizontal_field(form, f, kwargs) }}
          {% else%}
            {{ render_field(form, f, kwargs) }}
          {% endif%}
        {% endfor %}
    {% endif %}
{% endmacro %}

{% macro form_tag(form=None, action=None, class="") %}
    <form action="{{ action or '' }}" method="POST" role="form" class="{{class}}" enctype="multipart/form-data">
      {{ caller() }}
    </form>
{% endmacro %}

{% macro render_form_buttons(cancel_url, extra=None) %}
    <hr>
    <div class="form-group">
      <div class="submit-row">
        {% if cancel_url %}
          <a href="{{ cancel_url }}" class="btn btn-danger pull-left" role="button">Cancelar</a>
        {% endif %}
        {% if extra %}{{ extra }}{% endif %}
        <input type="submit" class="btn btn-primary pull-right"value="Guardar" />
      </div>
    </div>
{% endmacro %}

{% macro render_form(form, cancel_url, extra=None, form_opts=None, action=None, horizontal=False) -%}
    {% call form_tag(action=action, class=('form-horizontal' if horizontal else '') ) %}
        {{ render_form_fields(form, form_opts=form_opts, horizontal=horizontal) }}
        {{ render_form_buttons(cancel_url, extra) }}
    {% endcall %}
{% endmacro %}

{% macro create_box(title=None, box_extra_class='', minimize_tool=False) %}
<div class="box {{box_extra_class}}">
  {% if title%}
    <div class="box-header with-border">
      <h2 class="box-title">{{title}}</h2>
      <div class="box-tools pull-right">
        {% if minimize_tool %}
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
        {% endif %}
      </div>
    </div>
  {% endif %}
  <div class="box-body">
    {{ caller() }}
  </div>
</div>
{% endmacro %}

templates/index.html
{% extends "base.html" %}

{% block content %}
<section class="content">
  <div class="row">

    <div class="col-lg-3 col-xs-6">
      <div class="box box-danger">
        <div class="box-header with-border">
          <h3 class="box-title">Uso de disco</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
          </div>
        </div>
        <div class="box-body chart-responsive">
          <div class="chart" id="disk_space" style="height: 160px; position: relative;"></div>
        </div>
      </div>
    </div>

    <div class="col-lg-3 col-xs-6">
      <div class="small-box bg-aqua-gradient" title="Aqui puedes ver el estado de las campañas de email masivos y generar nuevas campañas">
        <div class="inner">
          <h3 id="indicador_mailing"><i class="fa fa-spinner fa-pulse fa-fw"></i></h3>
          <p>Campañas de Mailing</p>
        </div>
        <div class="icon">
          <i class="fa fa-envelope-o"></i>
        </div>
        <a href="{{url_for('campagnas.index')}}" class="small-box-footer">Ver detalles <i class="fa fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="col-lg-3 col-xs-6">
      <div class="small-box bg-green-gradient" title="Aqui puedes agregar nuevos usuarios a las listas de correo.">
        <div class="inner">
          <h3 id="indicador_lista_correos"><i class="fa fa-spinner fa-pulse fa-fw"></i></h3>
          <p>Listas de Correos</p>
        </div>
        <div class="icon">
          <i class="fa fa fa-th-list"></i>
        </div>
        <a href="/correos" class="small-box-footer">Ver detalles <i class="fa fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="col-lg-3 col-xs-6">
      <div class="small-box bg-red-gradient" title="Aqui puedes ver y editar las plantillas de correo">
        <div class="inner">
          <h3 id="indicador_plantillas"><i class="fa fa-spinner fa-pulse fa-fw"></i></h3>
          <p>Plantillas</p>
        </div>
        <div class="icon">
          <i class="fa fa-file-powerpoint-o"></i>
        </div>
        <a href="/plantillas" class="small-box-footer">Ver detalles <i class="fa fa-arrow-right"></i></a>
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block extra_css%}
<link rel="stylesheet" type="text/css" href="/static/plugins/morris/morris.css">
{% endblock %}

{% block extra_js%}
<script src="/static/plugins/morris/raphaeljs.min.js"></script>
<script src="/static/plugins/morris/morris.min.js"></script>
<script type="text/javascript">
  function fileSizeToHuman(size) {
      var e = (Math.log(size) / Math.log(1e3)) | 0;
      return +(size / Math.pow(1e3, e)).toFixed(2) + ' ' + ('kMGTPEZY'[e - 1] || '') + 'B';
  }
  $(function () {
    $.get('{{url_for(".statistics")}}', function(data){
      $("#indicador_mailing").text(data['mailing_count']);
      $("#indicador_plantillas").text(data['template_count']);
      $("#indicador_lista_correos").text(data['emails_list_count']);

    }, 'json')

    $.getJSON( "{{url_for('.disk_usage')}}", function( data ) {
      var donut = new Morris.Donut({
        element: 'disk_space',
        formatter: function (y, data) { return fileSizeToHuman(y) },
        resize: true,
        colors: ["#f56954", "#d2d6de"],
        data: [
          {label: "Espacio libre", value: data['free_space']},
          {label: "Espacio ocupado", value: data['used_disk']}
        ],
        hideHover: 'auto'
      });
    });
  });
</script>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Mailing | CDT</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/css/AdminLTE.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="/static/plugins/iCheck/square/blue.css">

</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="#l"><b>Mailing</b> CDT </a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Ingrese sus datos para iniciar session</p>

    <form method="post">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{category}} alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <h5>{{ message }}</h5>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      
      <input type="text" class="form-control" name="username" placeholder="Usuario" required autofocus> <br>
        <input type="password" class="form-control" name="password" placeholder="Contraseña" required>
        <br/><br/>
      <div class="row">
        <div class="col-xs-12">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Ingresar</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 2.2.3 -->
<script src="/static/js/jquery.min.js"></script>

<!-- Bootstrap 3.3.6 -->
<script src="/static/js/bootstrap.min.js"></script>
</body>
</html>

templates/logout.html
{% extends "base.html" %}

{% block body %}

    <link href="{{ url_for('static', filename='css/signin.css') }}" rel="stylesheet">
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class=flash>{{ message }}</div>
        {% endfor %}
    </div>
    <br>
    Si posee una cuenta puede iniciar <a href="/auth/login">sesión aquí</a>
{% endblock %}